USE sudoku;
DROP TABLE IF EXISTS GAME_MOVE;
DROP TABLE IF EXISTS GAMES;
DROP TABLE IF EXISTS MOVES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BOARDS;

CREATE TABLE USERS (
	id INT AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE BOARDS (
	id INT AUTO_INCREMENT,
    difficulty VARCHAR(50),
    PRIMARY KEY(id)
);

CREATE TABLE GAMES (
	user_id INT NOT NULL,
    board_id INT NOT NULL,
    start_time TIMESTAMP NOT NULL, -- DEFAULT NOW(),
    finish_time TIMESTAMP,
    CONSTRAINT FOREIGN KEY (user_id) REFERENCES USERS(id),
    CONSTRAINT FOREIGN KEY (board_id) REFERENCES BOARDS(id),
    PRIMARY KEY(user_id, board_id)
);

CREATE TABLE MOVES (
	id INT AUTO_INCREMENT,
	x INT CHECK(x >= 0 AND x <= 8) NOT NULL,
    y INT CHECK(y >= 0 AND y <= 8) NOT NULL,
    value INT CHECK(value >= 0 AND value <= 9) NOT NULL,
    move_time TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY(id)
);

CREATE TABLE GAME_MOVE (
    user_id INT NOT NULL,
    board_id INT NOT NULL,
	move_id INT NOT NULL,
    CONSTRAINT FOREIGN KEY (user_id) REFERENCES GAMES(user_id),
    CONSTRAINT FOREIGN KEY (board_id) REFERENCES GAMES(board_id),
    CONSTRAINT FOREIGN KEY (move_id) REFERENCES MOVES(id),
    PRIMARY KEY (user_id, board_id, move_id)
);